# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'niftuxui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(607, 583)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(60, 210, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button1.setFont(font)
        self.button1.setObjectName("button1")
        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(160, 210, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button2.setFont(font)
        self.button2.setObjectName("button2")
        self.button4 = QtWidgets.QPushButton(self.centralwidget)
        self.button4.setGeometry(QtCore.QRect(360, 210, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button4.setFont(font)
        self.button4.setObjectName("button4")
        self.button3 = QtWidgets.QPushButton(self.centralwidget)
        self.button3.setGeometry(QtCore.QRect(260, 210, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button3.setFont(font)
        self.button3.setObjectName("button3")
        self.button7 = QtWidgets.QPushButton(self.centralwidget)
        self.button7.setGeometry(QtCore.QRect(160, 310, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button7.setFont(font)
        self.button7.setObjectName("button7")
        self.button8 = QtWidgets.QPushButton(self.centralwidget)
        self.button8.setGeometry(QtCore.QRect(260, 310, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button8.setFont(font)
        self.button8.setObjectName("button8")
        self.button6 = QtWidgets.QPushButton(self.centralwidget)
        self.button6.setGeometry(QtCore.QRect(60, 310, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button6.setFont(font)
        self.button6.setObjectName("button6")
        self.button5 = QtWidgets.QPushButton(self.centralwidget)
        self.button5.setGeometry(QtCore.QRect(460, 210, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button5.setFont(font)
        self.button5.setObjectName("button5")
        self.button9 = QtWidgets.QPushButton(self.centralwidget)
        self.button9.setGeometry(QtCore.QRect(360, 310, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button9.setFont(font)
        self.button9.setObjectName("button9")
        self.button0 = QtWidgets.QPushButton(self.centralwidget)
        self.button0.setGeometry(QtCore.QRect(460, 310, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button0.setFont(font)
        self.button0.setObjectName("button0")
        self.buttonPaste = QtWidgets.QPushButton(self.centralwidget)
        self.buttonPaste.setGeometry(QtCore.QRect(360, 410, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.buttonPaste.setFont(font)
        self.buttonPaste.setObjectName("buttonPaste")
        self.buttonCopy = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCopy.setGeometry(QtCore.QRect(260, 410, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.buttonCopy.setFont(font)
        self.buttonCopy.setObjectName("buttonCopy")
        self.buttonBackdel = QtWidgets.QPushButton(self.centralwidget)
        self.buttonBackdel.setGeometry(QtCore.QRect(60, 410, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.buttonBackdel.setFont(font)
        self.buttonBackdel.setObjectName("buttonBackdel")
        self.buttonDel = QtWidgets.QPushButton(self.centralwidget)
        self.buttonDel.setGeometry(QtCore.QRect(160, 410, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.buttonDel.setFont(font)
        self.buttonDel.setObjectName("buttonDel")
        self.labelNIF = QtWidgets.QLabel(self.centralwidget)
        self.labelNIF.setGeometry(QtCore.QRect(69, 75, 441, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(134, 111, 87))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(134, 111, 87))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(134, 111, 87))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.labelNIF.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(50)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.labelNIF.setFont(font)
        self.labelNIF.setFocusPolicy(QtCore.Qt.NoFocus)
        self.labelNIF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelNIF.setWordWrap(False)
        self.labelNIF.setIndent(2)
        self.labelNIF.setOpenExternalLinks(False)
        self.labelNIF.setObjectName("labelNIF")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(60, 70, 461, 91))
        brush = QtGui.QBrush(QtGui.QColor(180, 150, 192))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView.setBackgroundBrush(brush)
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.raise_()
        self.button1.raise_()
        self.button2.raise_()
        self.button4.raise_()
        self.button3.raise_()
        self.button7.raise_()
        self.button8.raise_()
        self.button6.raise_()
        self.button5.raise_()
        self.button9.raise_()
        self.button0.raise_()
        self.buttonPaste.raise_()
        self.buttonCopy.raise_()
        self.buttonBackdel.raise_()
        self.buttonDel.raise_()
        self.labelNIF.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 607, 25))
        self.menubar.setObjectName("menubar")
        self.menuNIF = QtWidgets.QMenu(self.menubar)
        self.menuNIF.setObjectName("menuNIF")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCopiar = QtWidgets.QAction(MainWindow)
        self.actionCopiar.setObjectName("actionCopiar")
        self.actionPegar = QtWidgets.QAction(MainWindow)
        self.actionPegar.setObjectName("actionPegar")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.menuNIF.addAction(self.actionCopiar)
        self.menuNIF.addAction(self.actionPegar)
        self.menuNIF.addAction(self.actionSalir)
        self.menubar.addAction(self.menuNIF.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.button1, self.button2)
        MainWindow.setTabOrder(self.button2, self.button3)
        MainWindow.setTabOrder(self.button3, self.button4)
        MainWindow.setTabOrder(self.button4, self.button5)
        MainWindow.setTabOrder(self.button5, self.button6)
        MainWindow.setTabOrder(self.button6, self.button7)
        MainWindow.setTabOrder(self.button7, self.button8)
        MainWindow.setTabOrder(self.button8, self.button9)
        MainWindow.setTabOrder(self.button9, self.button0)
        MainWindow.setTabOrder(self.button0, self.buttonBackdel)
        MainWindow.setTabOrder(self.buttonBackdel, self.buttonDel)
        MainWindow.setTabOrder(self.buttonDel, self.buttonCopy)
        MainWindow.setTabOrder(self.buttonCopy, self.buttonPaste)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NIF (calcula letra)"))
        self.button1.setText(_translate("MainWindow", "1"))
        self.button2.setText(_translate("MainWindow", "2"))
        self.button4.setText(_translate("MainWindow", "4"))
        self.button3.setText(_translate("MainWindow", "3"))
        self.button7.setText(_translate("MainWindow", "7"))
        self.button8.setText(_translate("MainWindow", "8"))
        self.button6.setText(_translate("MainWindow", "6"))
        self.button5.setText(_translate("MainWindow", "5"))
        self.button9.setText(_translate("MainWindow", "9"))
        self.button0.setText(_translate("MainWindow", "0"))
        self.buttonPaste.setText(_translate("MainWindow", "📋"))
        self.buttonCopy.setText(_translate("MainWindow", "⎘"))
        self.buttonBackdel.setText(_translate("MainWindow", "◄"))
        self.buttonDel.setText(_translate("MainWindow", "🗑"))
        self.labelNIF.setText(_translate("MainWindow", "00000000-T"))
        self.menuNIF.setTitle(_translate("MainWindow", "NIF"))
        self.actionCopiar.setText(_translate("MainWindow", "&Copiar"))
        self.actionCopiar.setToolTip(_translate("MainWindow", "Copiar"))
        self.actionPegar.setText(_translate("MainWindow", "&Pegar"))
        self.actionSalir.setText(_translate("MainWindow", "&Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
